# Version 2023-03-05
name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: &global_matrix
        java: [ "17" ]
    outputs:
       id: ${{ steps.get-id.outputs.id }}
       tag: ${{ steps.get-id.outputs.tag }}
       version: ${{ steps.get-id.outputs.version }}
       rel_id: ${{ steps.get-id.outputs.rel_id }}

    steps:
      # Checkout Repo
      - uses: actions/checkout@v3

      # Create a variable with this plugin's name
      - id: get-id
        name: Compute needed variables
        run: |
          set -x
          id=$(echo ${{ github.repository }} | cut -d- -f2)
          echo "id=$id" >> $GITHUB_OUTPUT
          echo "id is '$id'"
          tag=$(echo ${{ github.ref }} | cut -d '/' -f3)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "tag is '$tag'"
          version=$(echo ${{ github.ref }} | cut -d '/' -f3 | cut -c 2-)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "version is '$version'"
          rel_id=$(curl -sL --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{github.repository}}/releases | jq -r --arg TAG "$tag" '.[] | select(.tag_name==$TAG) | .id')
          echo "rel_id=$rel_id" >> $GITHUB_OUTPUT
          echo "rel_id is '$rel_id'"

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-java${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java${{ matrix.java }}-maven-
            ${{ runner.os }}-

      - name: Igniterealtime CI Tooling
        run: |
          git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
          cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml

      - name: Build with Maven
        run:  mvn -B package

      - name: Stash the built artifacts
        uses: actions/upload-artifact@v4
        if: ${{ matrix.java == 17}}
        with:
          name: ${{ steps.get-id.outputs.id }}
          path: |
            target/${{ steps.get-id.outputs.id }}-openfire-plugin-assembly.jar
            target/${{ steps.get-id.outputs.id }}-integration-tests.jar
          retention-days: 3

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
        matrix: *global_matrix
    steps:

      - name: Download the built artifacts
        uses: actions/download-artifact@v4
        with:
            name: ${{ needs.build.outputs.id }}
            path: .

      - name: Rename built plugin (from artifacts)
        run: |
            mv ${{ needs.build.outputs.id }}-openfire-plugin-assembly.jar ${{ needs.build.outputs.id }}.jar

      - name: Run Openfire
        uses: igniterealtime/launch-openfire-action@main
        with:
            daily: true
            plugin: ./${{ needs.build.outputs.id }}.jar

      - name: Run XMPP interop tests
        uses: XMPP-Interop-Testing/xmpp-interop-tests-action@main
        with:
          domain: 'example.org'
          adminAccountUsername: 'admin'
          adminAccountPassword: 'admin'
          enabledSpecifications: 'XEP-0136,XEP-0313'
          extensionJar: ${{ needs.build.outputs.id }}-integration-tests.jar
          javaVersion: ${{ matrix.java }}

  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix: *global_matrix
    needs: [ build, test ]
    steps:
      - uses: actions/checkout@v3

      - name: Download the built plugin
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.id }}
          path: .

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
            java-version: ${{ matrix.java }}
            distribution: temurin

      - name: Igniterealtime CI Tooling
        run: |
          git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
          cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml

      - name: Conditionally Deploy to Igniterealtime Archiva
        id: deploy
        if: ${{ contains(github.repository, 'igniterealtime/') && ( ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || contains(github.ref, 'refs/tags/') ) && matrix.java == '17' }}
        run: mvn -B deploy -Dmaven.resolver.transport=wagon --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.IGNITE_REALTIME_MAVEN_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.IGNITE_REALTIME_MAVEN_PASSWORD }}

      - name: Conditionally Push Artifact to Github Release
        uses: actions/upload-release-asset@v1
        if: ${{ contains(github.repository, 'igniterealtime/') && github.event_name == 'push' && contains(github.ref, 'refs/tags/') && matrix.java == '17' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.build.outputs.rel_id }}/assets?name=${{ needs.build.outputs.id }}.jar
          asset_path: target/${{ needs.build.outputs.id }}-openfire-plugin-assembly.jar
          asset_name: ${{ needs.build.outputs.id }}.jar
          asset_content_type: application/java-archive
